#############################################################################
# Makefile for building gabot
# Generated by tmake at 00:30, 2002/04/08
#     Project: gabot
#    Template: app
#############################################################################

####### Compiler, tools and options

CC	=	gcc
CXX	=	g++
CFLAGS	=	-pipe -O2 -DNO_DEBUG
CXXFLAGS=	-pipe -O2 -DNO_DEBUG
INCPATH	=	-Iinclude -I$(QTDIR)/include
LINK	=	g++
LFLAGS	=	
LIBS	=	$(SUBLIBS) -L$(QTDIR)/lib -L/usr/X11R6/lib -lqt -lXext -lX11 -lm
MOC	=	$(QTDIR)/bin/moc
UIC	=	$(QTDIR)/bin/uic

TAR	=	tar -cf
GZIP	=	gzip -9f

####### Files

HEADERS =	include/bot.h \
		include/coordinate.h \
		include/direction.h \
		include/rotation.h \
		include/thing.h \
		include/garule.h \
		include/simplega.h \
		include/mainwindow.h \
		include/botview.h \
		include/team.h \
		include/gabot.h \
		include/arena.h \
		include/ball.h \
		include/teamparser.h \
		include/teamdata.h \
		include/game.h \
		include/random.h
SOURCES =	src/main.cpp \
		src/bot.cpp \
		src/garule.cpp \
		src/simplega.cpp \
		src/mainwindow.cpp \
		src/botview.cpp \
		src/team.cpp \
		src/gabot.cpp \
		src/arena.cpp \
		src/ball.cpp \
		src/teamparser.cpp \
		src/teamdata.cpp \
		src/game.cpp \
		src/random.cpp
OBJECTS =	src/main.o \
		src/bot.o \
		src/garule.o \
		src/simplega.o \
		src/mainwindow.o \
		src/botview.o \
		src/team.o \
		src/gabot.o \
		src/arena.o \
		src/ball.o \
		src/teamparser.o \
		src/teamdata.o \
		src/game.o \
		src/random.o
INTERFACES =	
UICDECLS =	
UICIMPLS =	
SRCMOC	=	include/moc_bot.cpp \
		include/moc_mainwindow.cpp \
		include/moc_botview.cpp \
		include/moc_team.cpp \
		include/moc_gabot.cpp \
		include/moc_arena.cpp \
		include/moc_ball.cpp \
		include/moc_game.cpp
OBJMOC	=	include/moc_bot.o \
		include/moc_mainwindow.o \
		include/moc_botview.o \
		include/moc_team.o \
		include/moc_gabot.o \
		include/moc_arena.o \
		include/moc_ball.o \
		include/moc_game.o
DIST	=	
TARGET	=	gabot
INTERFACE_DECL_PATH = .

####### Implicit rules

.SUFFIXES: .cpp .cxx .cc .C .c

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules


all: $(TARGET)

$(TARGET): $(UICDECLS) $(OBJECTS) $(OBJMOC) 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(LIBS)

moc: $(SRCMOC)

tmake: Makefile

Makefile: gabot.pro
	tmake gabot.pro -o Makefile

dist:
	$(TAR) gabot.tar gabot.pro $(SOURCES) $(HEADERS) $(INTERFACES) $(DIST)
	$(GZIP) gabot.tar

clean:
	-rm -f $(OBJECTS) $(OBJMOC) $(SRCMOC) $(UICIMPLS) $(UICDECLS) $(TARGET)
	-rm -f *~ core

####### Sub-libraries


###### Combined headers


####### Compile

src/main.o: src/main.cpp

src/bot.o: src/bot.cpp

src/garule.o: src/garule.cpp

src/simplega.o: src/simplega.cpp

src/mainwindow.o: src/mainwindow.cpp

src/botview.o: src/botview.cpp

src/team.o: src/team.cpp

src/gabot.o: src/gabot.cpp

src/arena.o: src/arena.cpp

src/ball.o: src/ball.cpp

src/teamparser.o: src/teamparser.cpp

src/teamdata.o: src/teamdata.cpp

src/game.o: src/game.cpp

src/random.o: src/random.cpp

include/moc_bot.o: include/moc_bot.cpp \
		include/bot.h \
		include/coordinate.h \
		include/direction.h \
		include/garule.h \
		include/rotation.h \
		include/thing.h \
		include/ball.h

include/moc_mainwindow.o: include/moc_mainwindow.cpp \
		include/mainwindow.h

include/moc_botview.o: include/moc_botview.cpp \
		include/botview.h \
		include/coordinate.h \
		include/direction.h

include/moc_team.o: include/moc_team.cpp \
		include/team.h \
		include/coordinate.h \
		include/direction.h

include/moc_gabot.o: include/moc_gabot.cpp \
		include/gabot.h \
		include/coordinate.h \
		include/direction.h \
		include/simplega.h \
		include/team.h

include/moc_arena.o: include/moc_arena.cpp \
		include/arena.h

include/moc_ball.o: include/moc_ball.cpp \
		include/ball.h \
		include/coordinate.h \
		include/direction.h

include/moc_game.o: include/moc_game.cpp \
		include/game.h \
		include/coordinate.h

include/moc_bot.cpp: include/bot.h
	$(MOC) include/bot.h -o include/moc_bot.cpp

include/moc_mainwindow.cpp: include/mainwindow.h
	$(MOC) include/mainwindow.h -o include/moc_mainwindow.cpp

include/moc_botview.cpp: include/botview.h
	$(MOC) include/botview.h -o include/moc_botview.cpp

include/moc_team.cpp: include/team.h
	$(MOC) include/team.h -o include/moc_team.cpp

include/moc_gabot.cpp: include/gabot.h
	$(MOC) include/gabot.h -o include/moc_gabot.cpp

include/moc_arena.cpp: include/arena.h
	$(MOC) include/arena.h -o include/moc_arena.cpp

include/moc_ball.cpp: include/ball.h
	$(MOC) include/ball.h -o include/moc_ball.cpp

include/moc_game.cpp: include/game.h
	$(MOC) include/game.h -o include/moc_game.cpp

